### ISSUE TITLE
JavaScript coder wanted

### ISSUE THREAD

**Issue by Daniel4-Scratch** [Snapcups/SnapCups#1]
I want help from someone that codes javascript so I can add the javascript version on to SnapCups

**Comment by R4356th** [comment]
How much JavaScript?

**Comment by Daniel4-Scratch** [comment]
Yeah basically, you can do it if want. I just need to test some other ones to make sure they work

**Comment by R4356th** [comment]
Done.

**Comment by Daniel4-Scratch** [comment]
Ok

**Comment by 18001767679** [comment]
me too
